module.exports = {
  apps: [
    {
      name: 'publisherhub_admin',
      cwd: '/home/dev/dev/publisherhub_admin',
      script: 'npm',
      args: 'start',
      watch: false,
      env: {
        PORT: 3000,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: 'publisherhub_backend',
      cwd: '/home/dev/dev/publisherhub_backend',
      script: 'node',
      args: 'server.js',
      watch: false,
      ignore_watch: ['node_modules', 'src/logs'],
      env: {
        PORT: 9072,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: 'publisherhub_frontend',
      cwd: '/home/dev/dev/publisherhub_frontend',
      script: 'npm',
      args: 'run dev',
      watch: false,
      env: {
        PORT: 9042,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: 'account_backend',
      cwd: '/home/dev/dev/account_backend',
      script: 'npm',
      args: 'start',
      watch: false,
      ignore_watch: ['node_modules', 'src/logs'],
      env: {
        PORT: 9048,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: 'account_frontend',
      cwd: '/home/dev/dev/account_frontend',
      script: './node_modules/.bin/react-scripts',
      args: 'start',
      watch: false,
      env: {
        PORT: 9041,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: 'support_backend',
      cwd: '/home/dev/dev/support_backend',
      script: './node_modules/.bin/nodemon',
      args: '--trace-warnings app.js',
      watch: false,
      ignore_watch: ['node_modules', 'src/logs'],
      env: {
        PORT: 9050,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: 'support_frontend',
      cwd: '/home/dev/dev/support_frontend',
      script: './node_modules/.bin/react-scripts',
      args: 'start',
      watch: false,
      env: {
        PORT: 9032,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: 'ajnavidya_frontend',
      cwd: '/home/dev/dev/ajnavidya_frontend',
      script: 'npm',
      args: 'run dev',
      env: {
        PORT: 9049,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: 'ajnavidya_store_backend',
      cwd: '/home/dev/dev/ajnavidya_store_backend',
      script: 'npm',
      args: 'run dev',
      watch: false,
      ignore_watch: ['node_modules', 'src/logs'],
      env: {
        PORT: 9047,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: 'mdm_backend',
      cwd: '/home/dev/dev/mdm_backend',
      script: 'npm',
      args: 'start',
      watch: false,
      ignore_watch: ['node_modules', 'src/logs'],
      env: {
        NODE_ENV: 'development',
        PORT: 9025,
      },
      max_restarts: 2,
    },
    {
      name: 'payment_gateway_backend',
      cwd: '/home/dev/dev/payment_gateway_backend',
      script: 'node',
      args: 'server.js',
      watch: false,
      ignore_watch: ['node_modules', 'src/logs'],
      env: {
        PORT: 9027,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: 'pm2_logger',
      cwd: '/home/dev/dev/pm2_logger',
      script: 'npm',
      args: 'start',
      watch: false,
      ignore_watch: ['node_modules', 'src/logs'],
      env: {
        PORT: 4343,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: "ajnalens_website",
      cwd: "/home/dev/dev/ajnalens_website/",
      script: "/home/dev/dev/nextStart.sh /home/dev/dev/ajnalens_website/ 9031",
      log_file: "/home/dev/pm2conf/logs/AJNALENS_WEBSITE.log",
      env: {
        NODE_ENV: "development",
        HTTP_FORWARDED_COUNT: 1,
      },
      max_restarts: 2,
    },
    {
      name: 'ajnalens_website_seo_backend',
      cwd: '/home/dev/dev/ajnalens_website_seo_backend',
      script: 'npm',
      args: 'start',
      watch: false,
      ignore_watch: ['node_modules', 'src/logs'],
      env: {
        PORT: 9030,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: 'ajna_blog_backend',
      cwd: '/home/dev/dev/ajna_blog_backend',
      script: 'npm',
      args: 'start',
      watch: false,
      ignore_watch: ['node_modules', 'src/logs'],
      env: {
        PORT: 9044,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
    {
      name: "seo_admin_frontend",
      cwd: "/home/dev/dev/seo_admin_frontend",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "development",
        PORT: 9045,
      },
      log_file: "/home/dev/pm2conf/logs/AJNALENS_WEBSITE.log",
      max_restarts: 2,
    },
    {
      name: "cart_frontend",
      cwd: "/home/dev/dev/cart_frontend",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "development",
        PORT: 9026,
      },
      log_file: "/home/dev/pm2conf/logs/AJNALENS_WEBSITE.log",
      max_restarts: 2,
    },
    {
      name: "mdm_frontend",
      cwd: "/home/dev/dev/mdm_frontend",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "development",
        PORT: 5173,
      },
      log_file: "/home/dev/pm2conf/logs/AJNALENS_WEBSITE.log",
      max_restarts: 2,
    },
    {
      name: "account_admin",
      cwd: "/home/dev/dev/account_admin",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "development",
        PORT: 9062,
      },
      log_file: "/home/dev/pm2conf/logs/ACCOUNT_ADMIN.log",
      max_restarts: 2,
    },
    {
      name: "mdm_ws",
      cwd: "/home/dev/dev/mdm_ws",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "development",
        PORT: 9023,
      },
      log_file: "/home/dev/pm2conf/logs/MDM_WS.log",
      max_restarts: 2,
    },
    {
      name: 'fastapi_app',
      cwd: '/home/dev/dev/ollama.py',
      script: 'uvicorn',
      args: 'app:app --host 0.0.0.0 --port 8090',
      watch: false,
      env: {
        PORT: 8090,
        NODE_ENV: 'development',
      },
      max_restarts: 2,
    },
  ],
};